/* =========================================================================
   MMLI RECEIPT GENERATOR — VERIFICATION PAGE LOGIC
   -------------------------------------------------------------------------
   TWO VERIFICATION PATHS:

   1. EMBEDDED (default, works for anyone, anywhere, no backend):
      Every QR code generated by this app encodes the receipt's key details
      directly in the link's query string (base64url, plus a short integrity
      checksum — see buildVerifyUrl() in script.js). When a link like that
      is opened, this page decodes and checksums it locally — no network
      lookup, no database, works on any device the instant the page loads.

   2. LOCAL HISTORY (fallback, this browser only):
      If a link only has ?id=... (no embedded payload — e.g. an old link,
      or one typed in by hand), we fall back to checking this browser's own
      saved Receipt History. That only finds receipts created on THIS
      device, which we say plainly in the result.

   FUTURE UPGRADE PATH:
   A central backend is optional, not required, for cross-device
   verification — the QR payload already provides that. A backend would
   mainly help with: revoking/voiding a receipt after the fact, or keeping
   a master ledger independent of any one device. To add one, extend
   lookupReceiptLocally() below with a fetch() call and merge its result
   with the embedded-payload path.
   ========================================================================= */

(function () {
  "use strict";

  const STORAGE_KEYS = {
    settings: "mmli_settings_v1",
    receipts: "mmli_receipts_v1"
  };

  function safeGet(key, fallback) {
    try {
      const raw = localStorage.getItem(key);
      if (raw === null || raw === undefined) return fallback;
      return JSON.parse(raw);
    } catch (e) {
      console.error("Storage read failed for", key, e);
      return fallback;
    }
  }

  function getSettings() {
    const defaults = { orgName: "Mind Masters Liberia Initiative", orgShort: "MMLI", logo: null };
    return Object.assign({}, defaults, safeGet(STORAGE_KEYS.settings, {}));
  }

  function getReceipts() {
    const stored = safeGet(STORAGE_KEYS.receipts, []);
    return Array.isArray(stored) ? stored : [];
  }

  /**
   * LOCAL-HISTORY lookup — only finds receipts saved on this device.
   * Used only as a fallback when a link has no embedded payload.
   */
  function lookupReceiptLocally(receiptId) {
    const receipts = getReceipts();
    return receipts.find(r => (r.receiptNo || "").toLowerCase() === (receiptId || "").toLowerCase()) || null;
  }

  /* ---- shared helpers (mirror script.js's buildVerifyUrl encoding) ---- */
  function b64UrlDecode(str) {
    let s = String(str || "").replace(/-/g, "+").replace(/_/g, "/");
    while (s.length % 4) s += "=";
    return decodeURIComponent(escape(atob(s)));
  }

  function fnv1aHex(str) {
    let h = 0x811c9dc5;
    for (let i = 0; i < str.length; i++) {
      h ^= str.charCodeAt(i);
      h = Math.imul(h, 0x01000193);
    }
    return (h >>> 0).toString(16).padStart(8, "0");
  }

  /**
   * Decodes the embedded payload from ?p=...&c=... if present.
   * Returns { ok:true, data, tampered:false } on a clean match,
   * { ok:true, data, tampered:true } if the checksum doesn't match
   * (link was edited/corrupted but still decodable),
   * or { ok:false } if there was no embedded payload at all.
   */
  function decodeEmbeddedPayload(params) {
    const p = params.get("p");
    const c = params.get("c");
    if (!p) return { ok: false };
    try {
      const json = b64UrlDecode(p);
      const data = JSON.parse(json);
      const tampered = !!c && fnv1aHex(json) !== c;
      return { ok: true, data, tampered };
    } catch (e) {
      console.error("Could not decode embedded verification payload", e);
      return { ok: false, malformed: true };
    }
  }

  function formatCurrency(amount, currencyCode) {
    const n = Number(amount);
    const safeN = isNaN(n) ? 0 : n;
    return (currencyCode || "") + " " + safeN.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }

  function formatDateLong(isoDateStr) {
    if (!isoDateStr) return "—";
    const parts = isoDateStr.split("-");
    if (parts.length !== 3) return isoDateStr;
    const d = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
    if (isNaN(d.getTime())) return isoDateStr;
    return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  }

  function escapeHtml(str) {
    if (str === null || str === undefined) return "";
    return String(str)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }

  function getParams() {
    return new URLSearchParams(window.location.search);
  }

  function renderNotFound(receiptId) {
    const card = document.getElementById("verify-card");
    card.innerHTML = `
      <div class="verify-icon">&#9888;</div>
      <div class="verify-banner invalid">RECEIPT NOT FOUND</div>
      <div class="verify-title">We could not verify this receipt</div>
      <div class="verify-sub">
        ${receiptId ? "No record for <strong>" + escapeHtml(receiptId) + "</strong> was found in this browser's saved history." : "No receipt information was found in this link."}
      </div>
      <div class="verify-scope-note">
        <strong>Why this can happen</strong>
        This link doesn't carry the receipt's verification data, so we could only check this browser's own Receipt History — and this receipt isn't in it. Scan the QR code directly from the original receipt for the most reliable result, or contact MMLI to confirm.
      </div>
      <a class="back-link" href="index.html">&larr; Back to Receipt Generator</a>
    `;
  }

  function renderTampered(receiptId) {
    const card = document.getElementById("verify-card");
    card.innerHTML = `
      <div class="verify-icon">&#9888;</div>
      <div class="verify-banner invalid">CHECK FAILED</div>
      <div class="verify-title">This link's details don't match its checksum</div>
      <div class="verify-sub">
        ${receiptId ? "The link claims to be for <strong>" + escapeHtml(receiptId) + "</strong>, but its data appears to have been altered or corrupted." : "This verification link appears to have been altered or corrupted."}
      </div>
      <div class="verify-scope-note">
        <strong>What this means</strong>
        The receipt details embedded in this link no longer match its integrity check. This can happen if the link was edited, partially copied, or tampered with. Don't treat this receipt as confirmed — ask for a fresh copy or scan the original QR code again.
      </div>
      <a class="back-link" href="index.html">&larr; Back to Receipt Generator</a>
    `;
  }

  function renderValid(receipt, scope) {
    const card = document.getElementById("verify-card");
    const isEmbedded = scope === "embedded";
    const subText = isEmbedded
      ? "This receipt's details were confirmed directly from its QR code — verified independently of any single device or database."
      : "This receipt matches a record saved in this browser's local history.";
    const scopeNote = isEmbedded
      ? "This confirms the receipt's data matches what was issued, wherever it's scanned. It does not check whether the receipt has since been cancelled or refunded by MMLI — for that, contact MMLI directly."
      : "This is a local-history match only: it confirms the receipt exists in the browser that created it. Receipts scanned from their original QR code verify on any device without this limitation.";
    card.innerHTML = `
      <div class="verify-icon valid">&#9989;</div>
      <div class="verify-banner valid">VALID RECEIPT</div>
      <div class="verify-title">Receipt verified</div>
      <div class="verify-sub">${subText}</div>
      <div class="verify-details">
        <div class="verify-row"><span class="k">Receipt Number</span><span class="v">${escapeHtml(receipt.receiptNo)}</span></div>
        <div class="verify-row"><span class="k">Payer</span><span class="v">${escapeHtml(receipt.payerName || "—")}</span></div>
        <div class="verify-row"><span class="k">Organization</span><span class="v">${escapeHtml(receipt.payerOrg || "—")}</span></div>
        <div class="verify-row"><span class="k">Category</span><span class="v">${escapeHtml(receipt.category || "—")}</span></div>
        <div class="verify-row"><span class="k">Method</span><span class="v">${escapeHtml(receipt.paymentMethod || "—")}</span></div>
        <div class="verify-row"><span class="k">Amount Paid</span><span class="v">${escapeHtml(formatCurrency(receipt.amountPaid, receipt.currency))}</span></div>
        <div class="verify-row"><span class="k">Date</span><span class="v">${escapeHtml(formatDateLong(receipt.date))}</span></div>
        <div class="verify-row"><span class="k">Payment Status</span><span class="v">${escapeHtml(receipt.status || "—")}</span></div>
      </div>
      <div class="verify-scope-note">
        <strong>About this verification</strong>
        ${scopeNote}
      </div>
      <a class="back-link" href="index.html">&larr; Back to Receipt Generator</a>
    `;
  }

  /** Normalize the embedded (short-key) payload to the same field names
   *  the local-history object uses, so renderValid() can treat them alike. */
  function normalizeEmbedded(p) {
    return {
      receiptNo: p.r || "",
      payerName: p.n || "",
      payerOrg: p.o || "",
      currency: p.c || p.cur || "LRD",
      amountPaid: p.a,
      date: p.d || "",
      status: p.s || "",
      category: p.g || "",
      paymentMethod: p.m || ""
    };
  }

  function init() {
    try {
      const settings = getSettings();
      document.getElementById("brand-name").textContent = settings.orgName || "Mind Masters Liberia Initiative";
      const logoImg = document.getElementById("header-logo-img");
      logoImg.src = settings.logo || MMLI_DEFAULT_LOGO_BASE64;

      const params = getParams();
      const receiptId = params.get("id") || "";
      const embedded = decodeEmbeddedPayload(params);

      if (embedded.ok && embedded.tampered) {
        renderTampered(receiptId || (embedded.data && embedded.data.r));
        return;
      }
      if (embedded.ok) {
        renderValid(normalizeEmbedded(embedded.data), "embedded");
        return;
      }

      // No embedded payload (or it was malformed) — fall back to this
      // browser's local Receipt History.
      const receipt = receiptId ? lookupReceiptLocally(receiptId) : null;
      if (receipt) renderValid(receipt, "local");
      else renderNotFound(receiptId);
    } catch (e) {
      console.error("Verification page error", e);
      const card = document.getElementById("verify-card");
      card.innerHTML = "<p>Something went wrong while checking this receipt. Please try again.</p>";
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
